version: '3'

services:

  db:
    image: postgres:13.2-alpine
    container_name: db
    env_file: .env
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}